select 
	PRODUCT_ID,
	PRODUCT_NAME,
	PRODUCT_CATEGORY,
	PRICE,
	SUPPLIER_ID,
	PRODUCT_COLOR,
	MANUFACTURING_DATE DATE,
	EXPIRATION_DATE DATE,
	WARRANTY_PERIOD,
	QUANTITY_IN_STOCK,
	RATING,
	SALES_VOLUME,
	WEIGHT_GRAMS,
	DISCOUNT_PERCENTAGE  
from { { source('de_project', 'product') } }